-- BlackStore-owned database only. No cross-database links.
-- CHECK lists from the spec use AND. PostgreSQL rejects comma-separated CHECK predicates.
-- flyway:executeInTransaction=false

CREATE ROLE blackstore_migration_owner NOINHERIT;
CREATE ROLE blackstore_app NOINHERIT;
CREATE ROLE blackstore_projection_worker NOINHERIT;
CREATE ROLE blackstore_outbox_worker NOINHERIT;
CREATE ROLE blackstore_auditor NOINHERIT;

CREATE TABLE companion_installation (singleton BOOLEAN PRIMARY KEY DEFAULT TRUE CHECK(singleton), storecore_installation_ref UUID NOT NULL UNIQUE, entitlement_state VARCHAR(16) NOT NULL, environment VARCHAR(16) NOT NULL, service_client_ref VARCHAR(160) NOT NULL UNIQUE, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), CHECK(entitlement_state IN ('DISABLED','ENABLED','SUSPENDED')), CHECK(environment IN ('TEST','DEVELOPMENT','PRODUCTION')));
CREATE TABLE roles (code VARCHAR(16) PRIMARY KEY, CHECK(code IN ('CASHIER','SUPERVISOR','OWNER','AUDITOR')));
CREATE TABLE staff_users (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, login VARCHAR(160) NOT NULL UNIQUE, password_hash VARCHAR(100) NOT NULL, role_code VARCHAR(16) NOT NULL REFERENCES roles(code) ON DELETE RESTRICT, active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), CHECK(password_hash LIKE '$2%'));
CREATE TABLE terminals (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, terminal_code VARCHAR(64) NOT NULL UNIQUE, active BOOLEAN NOT NULL DEFAULT TRUE);
CREATE TABLE cash_session_projection (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, terminal_id BIGINT NOT NULL REFERENCES terminals(id) ON DELETE RESTRICT, cashier_id BIGINT NOT NULL REFERENCES staff_users(id) ON DELETE RESTRICT, opened_at TIMESTAMPTZ NOT NULL, closed_at TIMESTAMPTZ NULL, opening_cash NUMERIC(14,2) NOT NULL DEFAULT 0, closing_cash_declared NUMERIC(14,2) NULL, status VARCHAR(24) NOT NULL DEFAULT 'OPEN', CHECK(opening_cash>=0), CHECK((status='OPEN' AND closed_at IS NULL AND closing_cash_declared IS NULL) OR (status IN ('CLOSED','RECONCILIATION_REQUIRED') AND closed_at IS NOT NULL AND closed_at>=opened_at AND closing_cash_declared IS NOT NULL)), CHECK(status IN ('OPEN','CLOSED','RECONCILIATION_REQUIRED')));
CREATE UNIQUE INDEX uq_open_cash_session_per_terminal ON cash_session_projection(terminal_id) WHERE status='OPEN';
CREATE TABLE sale_intents (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, client_instance_id UUID NOT NULL, device_id VARCHAR(80) NOT NULL, sale_id VARCHAR(80) NOT NULL, operation_id UUID NOT NULL, aggregate_operation_key UUID GENERATED ALWAYS AS (operation_id) STORED, cash_session_id BIGINT NOT NULL REFERENCES cash_session_projection(id) ON DELETE RESTRICT, created_by BIGINT NOT NULL REFERENCES staff_users(id) ON DELETE RESTRICT, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), canonical_path VARCHAR(80) NOT NULL DEFAULT '/blackstore-integration/v1', contract_version VARCHAR(32) NOT NULL, openapi_digest CHAR(64) NOT NULL, UNIQUE(client_instance_id, device_id, sale_id, operation_id), UNIQUE(id, operation_id));
CREATE TABLE sale_state_projection (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, sale_intent_id BIGINT NOT NULL, client_instance_id UUID NOT NULL, device_id VARCHAR(80) NOT NULL, sale_id VARCHAR(80) NOT NULL, operation_id UUID NOT NULL, aggregate_operation_key UUID NOT NULL, storecore_reservation_ref VARCHAR(160) NULL UNIQUE, reservation_receipt VARCHAR(128) NULL, contract_version VARCHAR(64) NULL, openapi_digest CHAR(64) NULL, accepted_price_versions JSONB NULL, reservation_expires_at TIMESTAMPTZ NULL, reconciliation_reason VARCHAR(500) NULL, status VARCHAR(32) NOT NULL DEFAULT 'PENDING_RESERVATION', fiscal_status VARCHAR(32) NOT NULL DEFAULT 'NOT_CONFIGURED', gross_sales NUMERIC(14,2) NOT NULL DEFAULT 0, discounts NUMERIC(14,2) NOT NULL DEFAULT 0, refunds NUMERIC(14,2) NOT NULL DEFAULT 0, net_sales NUMERIC(14,2) GENERATED ALWAYS AS (gross_sales-discounts) STORED, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(sale_intent_id,operation_id), UNIQUE(client_instance_id,device_id,sale_id,operation_id), FOREIGN KEY(sale_intent_id,operation_id) REFERENCES sale_intents(id,operation_id) ON DELETE RESTRICT, CHECK(aggregate_operation_key=operation_id), CHECK(status IN ('PENDING_RESERVATION','RESERVED','PAYMENT_CAPTURED','COMMIT_PENDING','COMMITTED','RELEASE_PENDING','RELEASED','RECONCILIATION_REQUIRED')), CHECK((status='PENDING_RESERVATION' AND storecore_reservation_ref IS NULL AND reservation_receipt IS NULL AND contract_version IS NULL AND openapi_digest IS NULL AND accepted_price_versions IS NULL AND reconciliation_reason IS NULL) OR (status='RECONCILIATION_REQUIRED' AND reconciliation_reason IS NOT NULL AND char_length(btrim(reconciliation_reason))>=3 AND ((storecore_reservation_ref IS NULL AND reservation_receipt IS NULL AND contract_version IS NULL AND openapi_digest IS NULL AND accepted_price_versions IS NULL) OR (storecore_reservation_ref IS NOT NULL AND reservation_receipt IS NOT NULL AND contract_version IS NOT NULL AND openapi_digest IS NOT NULL AND accepted_price_versions IS NOT NULL AND jsonb_typeof(accepted_price_versions)='array' AND jsonb_array_length(accepted_price_versions)>=1))) OR (status IN ('RESERVED','PAYMENT_CAPTURED','COMMIT_PENDING','COMMITTED','RELEASE_PENDING','RELEASED') AND storecore_reservation_ref IS NOT NULL AND reservation_receipt IS NOT NULL AND contract_version IS NOT NULL AND openapi_digest IS NOT NULL AND accepted_price_versions IS NOT NULL AND jsonb_typeof(accepted_price_versions)='array' AND jsonb_array_length(accepted_price_versions)>=1)), CHECK(fiscal_status IN ('NOT_CONFIGURED','PENDING','ISSUED','FAILED_RECONCILIATION')), CHECK(gross_sales>=0 AND discounts>=0 AND refunds>=0 AND discounts<=gross_sales));
CREATE TABLE sale_events (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, sale_id BIGINT NOT NULL REFERENCES sale_state_projection(id) ON DELETE RESTRICT, aggregate_operation_key UUID NOT NULL, event_type VARCHAR(32) NOT NULL, original_event_id BIGINT NULL REFERENCES sale_events(id) ON DELETE RESTRICT, actor_id BIGINT NOT NULL REFERENCES staff_users(id) ON DELETE RESTRICT, reason VARCHAR(500) NULL, evidence_ref VARCHAR(200) NULL, payload_redacted JSONB NOT NULL, occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(), CHECK(event_type IN ('INTENT_CREATED','RESERVE_COMMAND','RESERVED','PAYMENT_CAPTURED','COMMIT_COMMAND','COMMITTED','RELEASE_COMMAND','RELEASED','REVERSAL','ADJUSTMENT','RECONCILIATION')), CHECK(event_type NOT IN ('REVERSAL','ADJUSTMENT') OR (original_event_id IS NOT NULL AND reason IS NOT NULL AND evidence_ref IS NOT NULL)), CHECK(jsonb_typeof(payload_redacted) IN ('object','array')));
CREATE TABLE sale_lines (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, sale_id BIGINT NOT NULL REFERENCES sale_state_projection(id) ON DELETE RESTRICT, sku VARCHAR(128) NOT NULL, product_snapshot JSONB NOT NULL, quantity INTEGER NOT NULL, original_unit_price NUMERIC(14,2) NOT NULL, discount_amount NUMERIC(14,2) NOT NULL DEFAULT 0, effective_unit_price NUMERIC(14,2) NOT NULL, cost_amount NUMERIC(14,2) NULL, cost_source VARCHAR(100) NULL, cost_version VARCHAR(64) NULL, cost_effective_at TIMESTAMPTZ NULL, CHECK(jsonb_typeof(product_snapshot)='object' AND quantity>0 AND original_unit_price>=0 AND discount_amount>=0 AND discount_amount<=original_unit_price AND effective_unit_price=original_unit_price-discount_amount AND ((cost_amount IS NULL AND cost_source IS NULL AND cost_version IS NULL AND cost_effective_at IS NULL) OR (cost_amount>=0 AND cost_source IS NOT NULL AND cost_version IS NOT NULL AND cost_effective_at IS NOT NULL))));
CREATE TABLE payments (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, sale_id BIGINT NOT NULL REFERENCES sale_state_projection(id) ON DELETE RESTRICT, payment_method VARCHAR(24) NOT NULL, amount NUMERIC(14,2) NOT NULL, fee_amount NUMERIC(14,2) NOT NULL DEFAULT 0, provider_token_or_ref VARCHAR(160) NULL UNIQUE, card_brand VARCHAR(32) NULL, card_last4 CHAR(4) NULL, status VARCHAR(16) NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), CHECK(payment_method IN ('CASH','CARD','TRANSFER','OTHER') AND amount>0 AND fee_amount>=0 AND (card_last4 IS NULL OR card_last4 ~ '^[0-9]{4}$') AND status IN ('PENDING','CAPTURED','VOIDED','REFUNDED')));
CREATE TABLE expenses (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, cash_session_id BIGINT NOT NULL REFERENCES cash_session_projection(id) ON DELETE RESTRICT, category VARCHAR(80) NOT NULL, amount NUMERIC(14,2) NOT NULL, reason VARCHAR(500) NOT NULL, payment_method VARCHAR(24) NOT NULL, accrued_at TIMESTAMPTZ NOT NULL, paid_at TIMESTAMPTZ NULL, created_by BIGINT NOT NULL REFERENCES staff_users(id) ON DELETE RESTRICT, approved_by BIGINT NULL REFERENCES staff_users(id) ON DELETE RESTRICT, CHECK(amount>0 AND payment_method IN ('CASH','CARD','TRANSFER','OTHER')));
CREATE TABLE cash_ledger_events (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, cash_session_id BIGINT NOT NULL REFERENCES cash_session_projection(id) ON DELETE RESTRICT, event_type VARCHAR(24) NOT NULL, amount_delta NUMERIC(14,2) NOT NULL, sale_id BIGINT NULL REFERENCES sale_state_projection(id) ON DELETE RESTRICT, expense_id BIGINT NULL REFERENCES expenses(id) ON DELETE RESTRICT, original_event_id BIGINT NULL REFERENCES cash_ledger_events(id) ON DELETE RESTRICT, actor_id BIGINT NOT NULL REFERENCES staff_users(id) ON DELETE RESTRICT, reason VARCHAR(500) NULL, evidence_ref VARCHAR(200) NULL, occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(), CHECK(event_type IN ('OPENING','PAYMENT','REFUND','FEE','EXPENSE_ACCRUAL','EXPENSE_PAID','CLOSING_ADJUSTMENT','REVERSAL','ADJUSTMENT')), CHECK(amount_delta<>0 OR event_type='OPENING'), CHECK(event_type NOT IN ('REVERSAL','ADJUSTMENT','CLOSING_ADJUSTMENT') OR (original_event_id IS NOT NULL AND reason IS NOT NULL AND evidence_ref IS NOT NULL)));
CREATE TABLE storecore_inbox_events (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, client_instance_id UUID NOT NULL, device_id VARCHAR(80) NOT NULL, sale_id VARCHAR(80) NOT NULL, operation_id UUID NOT NULL, operation_kind VARCHAR(16) NOT NULL, state VARCHAR(16) NOT NULL, receipt VARCHAR(160) NULL, reservation_ref UUID NULL, response_hash CHAR(64) NOT NULL, contract_version VARCHAR(64) NOT NULL, openapi_digest CHAR(64) NOT NULL, payload_redacted JSONB NOT NULL, received_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(client_instance_id,device_id,sale_id,operation_id,operation_kind,response_hash), CHECK(operation_kind IN ('RESERVE','COMMIT','RELEASE','GET','RECONCILE') AND  state IN ('PENDING','RESERVED','COMMITTED','RELEASED','EXPIRED','RECONCILE_RESULT') AND jsonb_typeof(payload_redacted) IN ('object','array') AND ((operation_kind='RECONCILE' AND state='RECONCILE_RESULT' AND receipt IS NULL AND reservation_ref IS NULL) OR (state='PENDING' AND receipt IS NULL AND reservation_ref IS NULL) OR (state IN ('RESERVED','COMMITTED','RELEASED','EXPIRED') AND receipt IS NOT NULL AND reservation_ref IS NOT NULL))));
CREATE TABLE storecore_outbox_commands (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, client_instance_id UUID NOT NULL, device_id VARCHAR(80) NOT NULL, sale_id VARCHAR(80) NOT NULL, operation_id UUID NOT NULL, operation_kind VARCHAR(16) NOT NULL, canonical_path VARCHAR(80) NOT NULL DEFAULT '/blackstore-integration/v1', contract_version VARCHAR(32) NOT NULL, openapi_digest CHAR(64) NOT NULL, request_hash CHAR(64) NOT NULL, payload_redacted JSONB NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(client_instance_id,device_id,sale_id,operation_id,operation_kind), CHECK(operation_kind IN ('RESERVE','COMMIT','RELEASE') AND jsonb_typeof(payload_redacted) IN ('object','array')));
CREATE TABLE outbox_delivery_attempts (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, command_id BIGINT NOT NULL REFERENCES storecore_outbox_commands(id) ON DELETE RESTRICT, attempt_no INTEGER NOT NULL, state VARCHAR(16) NOT NULL DEFAULT 'PENDING', available_at TIMESTAMPTZ NOT NULL DEFAULT now(), started_at TIMESTAMPTZ NULL, completed_at TIMESTAMPTZ NULL, error_redacted VARCHAR(500) NULL, UNIQUE(command_id,attempt_no), CHECK(attempt_no>0 AND state IN ('PENDING','IN_PROGRESS','SENT','FAILED','DEAD')));
CREATE TABLE fiscal_production_authorizations (singleton BOOLEAN PRIMARY KEY DEFAULT TRUE CHECK(singleton), authorization_kind VARCHAR(32) NOT NULL, responsible_approval_ref VARCHAR(200) NOT NULL, accountant_approval_ref VARCHAR(200) NOT NULL, valid_from TIMESTAMPTZ NOT NULL, valid_until TIMESTAMPTZ NOT NULL, CHECK(authorization_kind IN ('EXTERNAL_MECHANISM_VALID','LAWFUL_EXCEPTION')), CHECK(valid_until>valid_from));
CREATE TABLE report_formula_config (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, formula_name VARCHAR(64) NOT NULL, version VARCHAR(32) NOT NULL, period_kind VARCHAR(16) NOT NULL, required_inputs JSONB NOT NULL, data_completeness_rule JSONB NOT NULL, effective_at TIMESTAMPTZ NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE, UNIQUE(formula_name,version), CHECK(formula_name IN ('CONTRIBUTION','REINVESTMENT_SUGGESTION','OWNER_SURPLUS_ESTIMATE') AND period_kind IN ('SHIFT','DAILY','MONTHLY') AND jsonb_typeof(required_inputs)='array' AND jsonb_typeof(data_completeness_rule)='object'));
CREATE TABLE data_retention_policies (purpose VARCHAR(80) PRIMARY KEY, retention_days INTEGER NOT NULL, legal_basis_ref VARCHAR(160) NOT NULL, reviewed_at TIMESTAMPTZ NOT NULL, CHECK(retention_days>0));
CREATE TABLE audit_events (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, actor_id BIGINT NULL REFERENCES staff_users(id) ON DELETE RESTRICT, event_type VARCHAR(100) NOT NULL, aggregate_type VARCHAR(64) NOT NULL, aggregate_id BIGINT NULL, payload_redacted JSONB NOT NULL, occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(), CHECK(jsonb_typeof(payload_redacted) IN ('object','array')));

CREATE FUNCTION reject_historical_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'immutable historical event'; END; $$;
CREATE FUNCTION enforce_initial_sale_projection() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.status<>'PENDING_RESERVATION' OR NEW.storecore_reservation_ref IS NOT NULL OR NEW.reservation_receipt IS NOT NULL OR NEW.contract_version IS NOT NULL OR NEW.openapi_digest IS NOT NULL OR NEW.accepted_price_versions IS NOT NULL OR NEW.reconciliation_reason IS NOT NULL OR NEW.reservation_expires_at IS NOT NULL THEN RAISE EXCEPTION 'app may insert only initial pending sale projection'; END IF; RETURN NEW; END; $$;
CREATE FUNCTION enforce_initial_cash_session_projection() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.status<>'OPEN' OR NEW.closed_at IS NOT NULL OR NEW.closing_cash_declared IS NOT NULL THEN RAISE EXCEPTION 'app may insert only initial open cash session projection'; END IF; RETURN NEW; END; $$;
CREATE FUNCTION enforce_sale_transition() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF TG_OP='UPDATE' AND NOT ((OLD.status='PENDING_RESERVATION' AND NEW.status IN ('RESERVED','RELEASE_PENDING','RECONCILIATION_REQUIRED')) OR (OLD.status='RESERVED' AND NEW.status IN ('PAYMENT_CAPTURED','RELEASE_PENDING','RECONCILIATION_REQUIRED')) OR (OLD.status='PAYMENT_CAPTURED' AND NEW.status IN ('COMMIT_PENDING','RELEASE_PENDING','RECONCILIATION_REQUIRED')) OR (OLD.status='COMMIT_PENDING' AND NEW.status IN ('COMMITTED','RECONCILIATION_REQUIRED')) OR (OLD.status='RELEASE_PENDING' AND NEW.status IN ('RELEASED','RECONCILIATION_REQUIRED'))) THEN RAISE EXCEPTION 'invalid sale transition'; END IF; RETURN NEW; END; $$;
CREATE FUNCTION enforce_production_fiscal_guard() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.status='COMMITTED' AND (SELECT environment FROM companion_installation WHERE singleton)='PRODUCTION' AND NOT EXISTS (SELECT 1 FROM fiscal_production_authorizations WHERE singleton AND valid_from<=now() AND valid_until>now()) THEN RAISE EXCEPTION 'production fiscal authorization required'; END IF; IF NEW.fiscal_status='NOT_CONFIGURED' AND (SELECT environment FROM companion_installation WHERE singleton)='PRODUCTION' THEN RAISE EXCEPTION 'NOT_CONFIGURED prohibited in production'; END IF; RETURN NEW; END; $$;
CREATE FUNCTION enforce_companion_production_enablement() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.environment='PRODUCTION' AND NEW.entitlement_state='ENABLED' AND NOT EXISTS (SELECT 1 FROM fiscal_production_authorizations WHERE singleton AND valid_from<=now() AND valid_until>now()) THEN RAISE EXCEPTION 'production companion enablement requires fiscal authorization'; END IF; RETURN NEW; END; $$;
CREATE FUNCTION enforce_cash_session_transition() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF TG_OP='UPDATE' AND NOT ((OLD.status='OPEN' AND NEW.status IN ('CLOSED','RECONCILIATION_REQUIRED')) OR OLD.status=NEW.status) THEN RAISE EXCEPTION 'invalid cash session transition'; END IF; RETURN NEW; END; $$;
CREATE FUNCTION enforce_cash_event() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.amount_delta=0 AND NEW.event_type<>'OPENING' THEN RAISE EXCEPTION 'zero cash event allowed only for OPENING'; END IF; IF NEW.event_type='OPENING' AND EXISTS (SELECT 1 FROM cash_ledger_events WHERE cash_session_id=NEW.cash_session_id AND event_type='OPENING') THEN RAISE EXCEPTION 'one OPENING event per cash session'; END IF; RETURN NEW; END; $$;
CREATE TRIGGER companion_production_enablement BEFORE INSERT OR UPDATE ON companion_installation FOR EACH ROW EXECUTE FUNCTION enforce_companion_production_enablement();
CREATE TRIGGER cash_session_projection_transition BEFORE UPDATE ON cash_session_projection FOR EACH ROW EXECUTE FUNCTION enforce_cash_session_transition();
CREATE TRIGGER cash_ledger_semantics BEFORE INSERT ON cash_ledger_events FOR EACH ROW EXECUTE FUNCTION enforce_cash_event();
CREATE TRIGGER initial_sale_projection BEFORE INSERT ON sale_state_projection FOR EACH ROW EXECUTE FUNCTION enforce_initial_sale_projection();
CREATE TRIGGER initial_cash_session_projection BEFORE INSERT ON cash_session_projection FOR EACH ROW EXECUTE FUNCTION enforce_initial_cash_session_projection();
CREATE TRIGGER sale_projection_transition BEFORE UPDATE ON sale_state_projection FOR EACH ROW EXECUTE FUNCTION enforce_sale_transition();
CREATE TRIGGER sale_projection_fiscal BEFORE INSERT OR UPDATE ON sale_state_projection FOR EACH ROW EXECUTE FUNCTION enforce_production_fiscal_guard();
CREATE TRIGGER immutable_sale_events BEFORE UPDATE OR DELETE ON sale_events FOR EACH ROW EXECUTE FUNCTION reject_historical_mutation();
CREATE TRIGGER immutable_cash_events BEFORE UPDATE OR DELETE ON cash_ledger_events FOR EACH ROW EXECUTE FUNCTION reject_historical_mutation();
CREATE TRIGGER immutable_expenses BEFORE UPDATE OR DELETE ON expenses FOR EACH ROW EXECUTE FUNCTION reject_historical_mutation();
CREATE TRIGGER immutable_inbox BEFORE UPDATE OR DELETE ON storecore_inbox_events FOR EACH ROW EXECUTE FUNCTION reject_historical_mutation();
CREATE TRIGGER immutable_commands BEFORE UPDATE OR DELETE ON storecore_outbox_commands FOR EACH ROW EXECUTE FUNCTION reject_historical_mutation();
CREATE TRIGGER immutable_audit BEFORE UPDATE OR DELETE ON audit_events FOR EACH ROW EXECUTE FUNCTION reject_historical_mutation();
REVOKE UPDATE, DELETE ON sale_events,cash_ledger_events,expenses,storecore_inbox_events,storecore_outbox_commands,audit_events FROM blackstore_app;
GRANT SELECT,INSERT ON cash_session_projection,sale_intents,sale_state_projection,sale_lines,payments,sale_events,cash_ledger_events,expenses,storecore_inbox_events,storecore_outbox_commands,audit_events TO blackstore_app;
GRANT USAGE,SELECT ON SEQUENCE cash_session_projection_id_seq,sale_intents_id_seq,sale_state_projection_id_seq,sale_lines_id_seq,payments_id_seq,sale_events_id_seq,cash_ledger_events_id_seq,expenses_id_seq,storecore_inbox_events_id_seq,storecore_outbox_commands_id_seq,audit_events_id_seq TO blackstore_app;
GRANT SELECT,INSERT,UPDATE ON sale_state_projection,cash_session_projection TO blackstore_projection_worker;
GRANT USAGE ON SEQUENCE sale_state_projection_id_seq,cash_session_projection_id_seq TO blackstore_projection_worker;
GRANT USAGE ON SEQUENCE outbox_delivery_attempts_id_seq TO blackstore_outbox_worker;
GRANT SELECT,INSERT,UPDATE ON outbox_delivery_attempts TO blackstore_outbox_worker;
