import { LocalDemoRepository } from './local-demo-repository';
import { DemoCashStatus, DemoMovementKind, DemoPaymentMethod, DemoRole, DemoSaleStatus, DemoScenario } from '../domain/demo-types';
describe('Isolated commercial demo repository',()=>{
 let repo:LocalDemoRepository;
 beforeEach(()=>repo=new LocalDemoRepository(()=>new Date('2026-10-08T14:00:00Z')));
 it('seeds the complete catalogue and fictitious customer list',()=>{expect(repo.snapshot().products.length).toBe(18);expect(repo.snapshot().customers.length).toBe(7);expect(new Set(repo.snapshot().products.map(p=>p.category)).size).toBe(4);});
 it('publishes immutable records',()=>{expect(Object.isFrozen(repo.snapshot().products[0])).toBeTrue();expect(Object.isFrozen(repo.snapshot().products)).toBeTrue();});
 it('records multiline sale exactly once with correct change, stock and cash',()=>{const before=repo.expectedCash();const p=repo.snapshot().products[0];const p2=repo.snapshot().products[1];repo.cart(p.id,2);repo.cart(p2.id,1);repo.discount(10);const total=Math.round((p.price*2+p2.price)*.9);const sale=repo.checkout('command',DemoPaymentMethod.Cash,total+10000,'');expect(sale.total).toBe(total);expect(sale.received-sale.total).toBe(10000);expect(repo.expectedCash()).toBe(before+total);expect(repo.snapshot().products[0].stock).toBe(p.stock-2);expect(repo.checkout('command',DemoPaymentMethod.Card,0,'')).toBe(sale);expect(repo.expectedCash()).toBe(before+total);expect(repo.snapshot().cart.length).toBe(0);});
 it('does not change cash for card sale and preserves old price snapshot',()=>{const p=repo.snapshot().products[0];const cash=repo.expectedCash();repo.cart(p.id,1);const sale=repo.checkout('card',DemoPaymentMethod.Card,0,'ref');repo.saveProduct({...p,price:p.price+10000});expect(sale.lines[0].price).toBe(p.price);expect(repo.expectedCash()).toBe(cash);});
 it('rejects stale cart without mutating any state',()=>{const p=repo.snapshot().products[0];repo.cart(p.id,1);repo.saveProduct({...p,price:p.price+1});const before=repo.snapshot();expect(()=>repo.checkout('stale',DemoPaymentMethod.Card,0,'')).toThrowError(/catálogo cambió/);expect(repo.snapshot()).toBe(before);});
 it('rejects insufficient cash, empty cart, negative and excessive stock quantities',()=>{expect(()=>repo.checkout('empty',DemoPaymentMethod.Cash,0,'')).toThrow();const p=repo.snapshot().products[0];expect(()=>repo.cart(p.id,-1)).toThrow();expect(()=>repo.cart(p.id,p.stock+1)).toThrow();repo.cart(p.id,1);expect(()=>repo.checkout('short',DemoPaymentMethod.Cash,1,'')).toThrowError(/no cubre/);});
 it('reverses once, restoring inventory and compensating cash',()=>{const p=repo.snapshot().products[0];const before=repo.expectedCash();repo.cart(p.id,1);const sale=repo.checkout('sale',DemoPaymentMethod.Cash,p.price,'');repo.reverse(sale.id,'Cambio demo');expect(repo.snapshot().sales[0].status).toBe(DemoSaleStatus.Reversed);expect(repo.snapshot().products[0].stock).toBe(p.stock);expect(repo.expectedCash()).toBe(before);expect(()=>repo.reverse(sale.id,'Otra vez')).toThrow();expect(repo.snapshot().stockMovements.length).toBe(2);});
 it('keeps command recoverable across simulated failure',()=>{repo.reset(DemoScenario.Error);repo.cart(repo.snapshot().products[0].id,1);const before=repo.snapshot();expect(()=>repo.checkout('retry',DemoPaymentMethod.Card,0,'')).toThrowError(/Reintentá/);expect(repo.snapshot()).toBe(before);const sale=repo.checkout('retry',DemoPaymentMethod.Card,0,'');expect(repo.checkout('retry',DemoPaymentMethod.Card,0,'')).toBe(sale);});
 it('prevents sale with closed cash and supports opening',()=>{repo.reset(DemoScenario.Closed);repo.cart('p1',1);expect(()=>repo.checkout('closed',DemoPaymentMethod.Card,0,'')).toThrowError(/Abrí la caja/);const history=repo.snapshot().movements.length;repo.openCash(100000);expect(repo.snapshot().cashStatus).toBe(DemoCashStatus.Open);expect(repo.snapshot().movements.length).toBe(history+1);expect(repo.expectedCash()).toBe(100000);});
 it('records expenses and requires an explanation for closing differences',()=>{repo.moveCash(DemoMovementKind.Expense,10000,'Bolsas');const expected=repo.expectedCash();expect(()=>repo.closeCash(expected-1,'')).toThrow();repo.closeCash(expected-1,'Diferencia demo');expect(repo.snapshot().cashCount?.expected).toBe(expected);expect(repo.snapshot().cashStatus).toBe(DemoCashStatus.Closed);});
 it('enforces fictitious role permissions and neutral unknown states',()=>{repo.setRole(DemoRole.Cashier);expect(()=>repo.adjust('p1',2,'test')).toThrow();expect(()=>repo.discount(2)).toThrow();repo.setRole(DemoRole.Unknown);expect(()=>repo.checkout('unknown',DemoPaymentMethod.Cash,0,'')).toThrow();expect(DemoPaymentMethod.fromWire('evil')).toBe(DemoPaymentMethod.Unknown);expect(DemoCashStatus.fromWire('evil').canSell).toBeFalse();expect(DemoSaleStatus.fromWire('evil').canReverse).toBeFalse();});
 it('validates SKU/email and maintains nonnegative stock',()=>{const p=repo.snapshot().products[0];expect(()=>repo.saveProduct({...p,id:'',sku:repo.snapshot().products[1].sku})).toThrow();expect(()=>repo.adjust(p.id,-p.stock-1,'adjust')).toThrow();expect(()=>repo.saveCustomer({id:'',name:'Demo',email:'invalid',phone:''})).toThrow();repo.saveCustomer({id:'',name:'Nueva Demo',email:'new@example.invalid',phone:''});expect(repo.snapshot().customers.length).toBe(8);});
 it('reset returns deterministic seed without reusing receipts',()=>{repo.cart('p1',1);repo.checkout('one',DemoPaymentMethod.Card,0,'');repo.reset(DemoScenario.Empty);expect(repo.snapshot().sales.length).toBe(0);expect(repo.snapshot().cart.length).toBe(0);expect(repo.snapshot().customers.length).toBe(7);});
});
