import { LocalDemoRepository } from './local-demo-repository';
import { DemoCashStatus, DemoMovementKind, DemoPaymentStatus, DemoPaymentMethod, DemoRole, DemoSaleStatus, DemoScenario } from '../domain/demo-types';
describe('Isolated commercial demo repository',()=>{
 let repo:LocalDemoRepository;
 beforeEach(()=>repo=new LocalDemoRepository(()=>new Date('2026-10-08T14:00:00Z')));
 const approveCard=(command:string)=>{repo.beginPayment(command,DemoPaymentMethod.Card,0,'ref');const attempt=repo.resolvePayment(command,DemoPaymentStatus.Approved);return repo.snapshot().sales.find(s=>s.id===attempt.saleId)!;};
 it('seeds the complete catalogue and fictitious customer list',()=>{expect(repo.snapshot().products.length).toBe(18);expect(repo.snapshot().customers.length).toBe(7);expect(new Set(repo.snapshot().products.map(p=>p.category)).size).toBe(4);});
 it('publishes immutable records',()=>{expect(Object.isFrozen(repo.snapshot().products[0])).toBeTrue();expect(Object.isFrozen(repo.snapshot().products)).toBeTrue();});
 it('records multiline sale exactly once with correct change, stock and cash',()=>{const before=repo.expectedCash();const p=repo.snapshot().products[0];const p2=repo.snapshot().products[1];repo.cart(p.id,2);repo.cart(p2.id,1);repo.discount(10);const total=Math.round((p.price*2+p2.price)*.9);const sale=repo.checkout('command',DemoPaymentMethod.Cash,total+10000,'');expect(sale.total).toBe(total);expect(sale.received-sale.total).toBe(10000);expect(repo.expectedCash()).toBe(before+total);expect(repo.snapshot().products[0].stock).toBe(p.stock-2);expect(repo.checkout('command',DemoPaymentMethod.Card,0,'')).toBe(sale);expect(repo.expectedCash()).toBe(before+total);expect(repo.snapshot().cart.length).toBe(0);});
 it('does not change cash for approved card sale and preserves old price snapshot',()=>{const p=repo.snapshot().products[0];const cash=repo.expectedCash();repo.cart(p.id,1);const sale=approveCard('card');repo.saveProduct({...p,price:p.price+10000});expect(sale.lines[0].price).toBe(p.price);expect(repo.expectedCash()).toBe(cash);});
 it('rejects stale cart without mutating any state',()=>{const p=repo.snapshot().products[0];repo.cart(p.id,1);repo.saveProduct({...p,price:p.price+1});const before=repo.snapshot();expect(()=>repo.beginPayment('stale',DemoPaymentMethod.Card,0,'')).toThrowError(/catálogo cambió/);expect(repo.snapshot()).toBe(before);});
 it('rejects insufficient cash, empty cart, negative and excessive stock quantities',()=>{expect(()=>repo.checkout('empty',DemoPaymentMethod.Cash,0,'')).toThrow();const p=repo.snapshot().products[0];expect(()=>repo.cart(p.id,-1)).toThrow();expect(()=>repo.cart(p.id,p.stock+1)).toThrow();repo.cart(p.id,1);expect(()=>repo.checkout('short',DemoPaymentMethod.Cash,1,'')).toThrowError(/no cubre/);});
 it('reverses once, restoring inventory and compensating cash',()=>{const p=repo.snapshot().products[0];const before=repo.expectedCash();repo.cart(p.id,1);const sale=repo.checkout('sale',DemoPaymentMethod.Cash,p.price,'');repo.reverse(sale.id,'Cambio demo');expect(repo.snapshot().sales[0].status).toBe(DemoSaleStatus.Reversed);expect(repo.snapshot().products[0].stock).toBe(p.stock);expect(repo.expectedCash()).toBe(before);expect(()=>repo.reverse(sale.id,'Otra vez')).toThrow();expect(repo.snapshot().stockMovements.length).toBe(2);});
 it('keeps command recoverable across simulated failure',()=>{repo.reset(DemoScenario.Error);repo.cart(repo.snapshot().products[0].id,1);const before=repo.snapshot();expect(()=>repo.beginPayment('retry',DemoPaymentMethod.Card,0,'')).toThrowError(/Reintentá/);expect(repo.snapshot()).toBe(before);const sale=approveCard('retry');expect(repo.checkout('retry',DemoPaymentMethod.Card,0,'')).toBe(sale);});
 it('prevents sale with closed cash and supports opening',()=>{repo.reset(DemoScenario.Closed);repo.cart('p1',1);expect(()=>repo.beginPayment('closed',DemoPaymentMethod.Card,0,'')).toThrowError(/Abrí la caja/);const history=repo.snapshot().movements.length;repo.openCash(100000);expect(repo.snapshot().cashStatus).toBe(DemoCashStatus.Open);expect(repo.snapshot().movements.length).toBe(history+1);expect(repo.expectedCash()).toBe(100000);});
 it('records expenses and requires an explanation for closing differences',()=>{repo.moveCash(DemoMovementKind.Expense,10000,'Bolsas');const expected=repo.expectedCash();expect(()=>repo.closeCash(expected-1,'')).toThrow();repo.closeCash(expected-1,'Diferencia demo');expect(repo.snapshot().cashCount?.expected).toBe(expected);expect(repo.snapshot().cashStatus).toBe(DemoCashStatus.Closed);});
 it('closes seeded and post-sale cash without differences when ARS are translated to cents once',()=>{const seeded=repo.expectedCash();repo.closeCash(Math.round((seeded/100)*100),'');expect(repo.snapshot().cashCount?.declared).toBe(seeded);expect(repo.snapshot().cashCount?.expected).toBe(seeded);repo.reset(DemoScenario.Normal);repo.cart('p1',1);repo.checkout('cash-before-close',DemoPaymentMethod.Cash,1250000,'');const afterSale=repo.expectedCash();expect(afterSale).toBe(seeded+1250000);repo.closeCash(Math.round((afterSale/100)*100),'');expect(repo.snapshot().cashCount?.declared).toBe(afterSale);expect(repo.snapshot().cashCount?.expected).toBe(afterSale);});
 it('enforces fictitious role permissions and neutral unknown states',()=>{repo.setRole(DemoRole.Cashier);expect(()=>repo.adjust('p1',2,'test')).toThrow();expect(()=>repo.discount(2)).toThrow();repo.setRole(DemoRole.Unknown);expect(()=>repo.checkout('unknown',DemoPaymentMethod.Cash,0,'')).toThrow();expect(DemoPaymentMethod.fromWire('evil')).toBe(DemoPaymentMethod.Unknown);expect(DemoCashStatus.fromWire('evil').canSell).toBeFalse();expect(DemoSaleStatus.fromWire('evil').canReverse).toBeFalse();});
 it('validates SKU/email and maintains nonnegative stock',()=>{const p=repo.snapshot().products[0];expect(()=>repo.saveProduct({...p,id:'',sku:repo.snapshot().products[1].sku})).toThrow();expect(()=>repo.adjust(p.id,-p.stock-1,'adjust')).toThrow();expect(()=>repo.saveCustomer({id:'',name:'Demo',email:'invalid',phone:''})).toThrow();repo.saveCustomer({id:'',name:'Nueva Demo',email:'new@example.invalid',phone:''});expect(repo.snapshot().customers.length).toBe(8);});
 it('reset returns deterministic seed without reusing receipts',()=>{repo.cart('p1',1);approveCard('one');repo.reset(DemoScenario.Empty);expect(repo.snapshot().sales.length).toBe(0);expect(repo.snapshot().cart.length).toBe(0);expect(repo.snapshot().customers.length).toBe(7);});
 for(const method of [DemoPaymentMethod.Card,DemoPaymentMethod.Transfer,DemoPaymentMethod.QR]){
  it(`${method.label}: pending payment is isolated and approval commits exactly once`,()=>{const p=repo.snapshot().products[0];repo.cart(p.id,1);const before=repo.snapshot();const cash=repo.expectedCash();const attempt=repo.beginPayment('payment',method,0,'ref-demo');expect(attempt.status).toBe(DemoPaymentStatus.Pending);expect(repo.snapshot().sales).toBe(before.sales);expect(repo.snapshot().products).toBe(before.products);expect(repo.expectedCash()).toBe(cash);expect(()=>repo.cart(p.id,2)).toThrowError(/pendiente/);expect(()=>repo.closeCash(cash,'')).toThrowError(/pendiente/);const approved=repo.resolvePayment(attempt.id,DemoPaymentStatus.Approved);expect(approved.status).toBe(DemoPaymentStatus.Approved);expect(repo.snapshot().products[0].stock).toBe(p.stock-1);expect(repo.snapshot().sales.length).toBe(before.sales.length+1);expect(repo.resolvePayment(attempt.id,DemoPaymentStatus.Approved)).toBe(approved);expect(repo.expectedCash()).toBe(cash);});
  for(const status of [DemoPaymentStatus.Rejected,DemoPaymentStatus.Cancelled])it(`${method.label}: ${status.label} preserves cart and allows a new attempt`,()=>{repo.cart('p1',1);repo.discount(10);repo.selectCustomer('c1');const before=repo.snapshot();repo.beginPayment('first',method,0,'');repo.resolvePayment('first',status);expect(repo.snapshot().products).toBe(before.products);expect(repo.snapshot().sales).toBe(before.sales);expect(repo.snapshot().movements).toBe(before.movements);expect(repo.snapshot().cart).toBe(before.cart);expect(repo.snapshot().customerId).toBe('c1');expect(repo.snapshot().discount).toBe(10);expect(repo.resolvePayment('first',DemoPaymentStatus.Approved).status).toBe(status);repo.beginPayment('retry',method,0,'');const approved=repo.resolvePayment('retry',DemoPaymentStatus.Approved);expect(approved.saleId).toBeDefined();});
 }
 it('mixed electronic payment moves only cash portion and reverses coherently',()=>{repo.cart('p1',1);const cash=repo.expectedCash();repo.beginPayment('mixed',DemoPaymentMethod.QR,600000,'mixed-ref',500000);expect(repo.expectedCash()).toBe(cash);const approved=repo.resolvePayment('mixed',DemoPaymentStatus.Approved);const sale=repo.snapshot().sales[0];expect(sale.cashAmount).toBe(500000);expect(sale.received-sale.cashAmount).toBe(100000);expect(repo.expectedCash()).toBe(cash+500000);repo.reverse(approved.saleId!,'Devolución demo');expect(repo.expectedCash()).toBe(cash);});
 it('rejects invalid mixed amounts and unknown resolutions without side effects',()=>{repo.cart('p1',1);const before=repo.snapshot();expect(()=>repo.beginPayment('unknown',DemoPaymentMethod.Unknown,0,'')).toThrow();expect(()=>repo.beginPayment('mixed',DemoPaymentMethod.QR,0,'',1)).toThrow();expect(()=>repo.beginPayment('over',DemoPaymentMethod.QR,repo.total(),' ',repo.total())).toThrow();expect(repo.snapshot()).toBe(before);repo.beginPayment('pending',DemoPaymentMethod.QR,0,'');expect(()=>repo.resolvePayment('pending',DemoPaymentStatus.Unknown)).toThrow();expect(repo.snapshot().payment?.status).toBe(DemoPaymentStatus.Pending);expect(DemoPaymentStatus.fromWire('untrusted')).toBe(DemoPaymentStatus.Unknown);});
 it('cashier sells and registers customers while managerial commands remain unavailable',()=>{repo.setRole(DemoRole.Cashier);repo.saveCustomer({id:'',name:'Cliente caja demo',email:'cashier@example.invalid',phone:''});repo.cart('p1',1);const sale=approveCard('cashier-sale');expect(sale.cashier).toContain('Cajero');const before=repo.snapshot();expect(()=>repo.saveProduct({...before.products[0],price:1})).toThrow();expect(()=>repo.reverse(sale.id,'test')).toThrow();expect(()=>repo.closeCash(repo.expectedCash(),'test')).toThrow();expect(()=>repo.moveCash(DemoMovementKind.Expense,100,'test')).toThrow();expect(repo.snapshot()).toBe(before);});
 it('pending payment survives module navigation and cannot change its cart, customer, stock or role',()=>{repo.cart('p1',1);repo.beginPayment('pending',DemoPaymentMethod.Transfer,0,'demo');const before=repo.snapshot();expect(()=>repo.discount(10)).toThrow();expect(()=>repo.clearCart()).toThrow();expect(()=>repo.selectCustomer('c1')).toThrow();expect(()=>repo.adjust('p1',1,'test')).toThrow();expect(()=>repo.setRole(DemoRole.Cashier)).toThrow();expect(()=>repo.saveProduct({...before.products[0],active:false})).toThrow();expect(repo.snapshot()).toBe(before);repo.resolvePayment('pending',DemoPaymentStatus.Cancelled);repo.cart('p1',2);expect(repo.snapshot().cart[0].quantity).toBe(2);});
});
