import { test, expect } from '@playwright/test';
test('all demo routes stay isolated from business HTTP and render responsive shells',async({page})=>{
 const api:string[]=[];page.on('request',request=>{if(request.url().includes('/api/')||request.url().includes(':808'))api.push(request.url());});
 for(const width of [1440,768,390]){await page.setViewportSize({width,height:1000});for(const route of ['','pos','pago','productos','inventario','clientes','ventas','caja','reportes','escenarios','ventas/missing']){await page.goto('/demo/'+route);await expect(page.locator('h1')).toBeVisible();await expect(page.getByText('Datos de demostración',{exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);if(['','pos','pago','inventario','reportes'].includes(route))await page.screenshot({path:`demo-test-results/screenshots/${width}-${route||'home'}.png`,fullPage:true});}}
 expect(api).toEqual([]);
});
test('multiline sale, explicit payment, receipt, inventory, cash and reversal',async({page})=>{
 await page.goto('/demo/pos');const first=page.locator('.product-card').first();await first.getByRole('button',{name:'Agregar',exact:false}).click();await page.locator('.product-card').nth(1).getByRole('button',{name:'Agregar',exact:false}).click();await page.locator('.quantity').first().getByRole('button',{name:'Aumentar cantidad'}).click();await expect(page.locator('.cart-line')).toHaveCount(2);
 await page.getByRole('link',{name:'Continuar al pago'}).click();await expect(page.getByRole('button',{name:'Confirmar cobro'})).toBeDisabled();await page.getByRole('radio',{name:'Efectivo',exact:true}).check();await page.getByLabel('Efectivo recibido (ARS)').fill('100000');await page.getByRole('button',{name:'Confirmar cobro'}).click();await expect(page.locator('.receipt h2')).toHaveText('V-101');await expect(page.locator('.receipt')).toContainText('2 × Remera esencial');
 for(const width of [1440,768,390]){await page.setViewportSize({width,height:1000});await page.screenshot({path:`demo-test-results/screenshots/${width}-receipt.png`,fullPage:true});}
 await page.getByLabel('Motivo de devolución').fill('Cambio de talle demo');await page.getByRole('button',{name:'Registrar devolución'}).click();await page.getByRole('button',{name:'Confirmar',exact:true}).click();await expect(page.locator('.receipt')).toContainText('Devuelta');await expect(page.getByRole('button',{name:'Registrar devolución'})).toHaveCount(0);
 await page.setViewportSize({width:1440,height:1000});await page.getByRole('link',{name:'Inventario',exact:true}).click();await expect(page.locator('.product-card').first()).toContainText('2 disponibles');await page.locator('.product-card').first().getByRole('button',{name:'Ajustar stock'}).click();await expect(page.getByRole('dialog')).toContainText('Devolución V-101');
});
test('product/customer CRUD, cash controls, exports and scenario reset produce outcomes',async({page})=>{
 await page.goto('/demo/productos');await page.getByRole('button',{name:'Crear producto'}).click();await page.getByLabel('Nombre',{exact:true}).fill('Producto nuevo demo');await page.getByLabel('SKU',{exact:true}).fill('DEMO-NEW');await page.getByLabel('Precio (ARS)').fill('3500');await page.getByRole('button',{name:'Guardar producto'}).click();await expect(page.getByRole('heading',{name:'Producto nuevo demo'})).toBeVisible();
 await page.getByRole('link',{name:'Clientes',exact:true}).click();await page.getByRole('button',{name:'Nuevo cliente'}).click();await page.getByLabel('Nombre',{exact:true}).fill('Cliente prueba demo');await page.getByLabel('Email opcional').fill('cliente@example.invalid');await page.getByRole('button',{name:'Guardar cliente'}).click();await expect(page.getByRole('heading',{name:'Cliente prueba demo'})).toBeVisible();
 await page.getByRole('link',{name:'Caja',exact:true}).click();await page.getByLabel('Importe (ARS)').fill('2000');await page.getByLabel('Motivo / categoría').fill('Bolsas demo');await page.getByRole('button',{name:'Guardar movimiento'}).click();await expect(page.getByText('Bolsas demo',{exact:false}).last()).toBeVisible();
 await page.getByRole('link',{name:'Ventas',exact:true}).click();const download=page.waitForEvent('download');await page.getByRole('button',{name:'Exportar CSV'}).click();expect((await download).suggestedFilename()).toBe('ventas-demo.csv');
 await page.getByRole('link',{name:'Escenarios',exact:true}).click();await page.getByLabel('Estado inicial').selectOption('closed');await page.getByRole('button',{name:'Cargar escenario'}).click();await page.getByRole('button',{name:'Confirmar',exact:true}).click();await expect(page.locator('.cash-pill')).toContainText('Caja cerrada');
});
test('inventory adjustments, edit and activation produce coherent outcomes',async({page})=>{
 await page.goto('/demo/inventario');await page.locator('.product-card').first().getByRole('button',{name:'Ajustar stock'}).click();await page.getByLabel('Ajuste de unidades').fill('3');await page.getByLabel('Motivo',{exact:true}).fill('Reposición demo');await page.getByRole('button',{name:'Registrar ajuste'}).click();await expect(page.getByRole('dialog')).toContainText('5 disponibles');await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);
 await page.getByRole('link',{name:'Productos',exact:true}).click();await page.locator('.product-card').first().getByRole('button',{name:'Editar',exact:true}).click();await page.getByLabel('Nombre',{exact:true}).fill('Remera actualizada demo');await page.getByRole('button',{name:'Guardar producto'}).click();await expect(page.locator('.product-card').first()).toContainText('Remera actualizada demo');await page.locator('.product-card').first().getByRole('button',{name:'Desactivar',exact:true}).click();await expect(page.locator('.product-card').first()).toContainText('Inactivo');await page.locator('.product-card').first().getByRole('button',{name:'Activar',exact:true}).click();
 await page.getByRole('link',{name:'Clientes',exact:true}).click();await page.locator('.customer-grid article').nth(1).getByRole('button',{name:'Editar',exact:true}).click();await page.getByLabel('Nombre',{exact:true}).fill('Ana actualizada Demo');await page.getByRole('button',{name:'Guardar cliente'}).click();await page.locator('.customer-grid article').nth(1).getByRole('button',{name:'Ver historial'}).click();await expect(page.getByRole('dialog')).toContainText('Ana actualizada Demo');await page.getByRole('button',{name:'Iniciar venta para este cliente'}).click();await expect(page.locator('.cart select')).toHaveValue('c1');
});
test('retry, cancel, card payment, receipt download and report exports',async({page})=>{
 await page.goto('/demo/escenarios');await page.getByLabel('Estado inicial').selectOption('error');await page.getByRole('button',{name:'Cargar escenario'}).click();await page.getByRole('button',{name:'Confirmar',exact:true}).click();await page.getByRole('link',{name:'Nueva venta',exact:true}).first().click();await page.locator('.product-card').first().getByRole('button',{name:'Agregar',exact:false}).click();await page.getByRole('link',{name:'Continuar al pago'}).click();await page.getByRole('link',{name:'Cancelar pago y conservar carrito'}).click();await expect(page.locator('.cart-line')).toHaveCount(1);await page.getByRole('link',{name:'Continuar al pago'}).click();await page.getByRole('radio',{name:'Tarjeta',exact:true}).check();await page.getByRole('button',{name:'Confirmar cobro'}).click();await expect(page.getByRole('alert')).toContainText('Reintentá');await page.getByRole('button',{name:'Confirmar cobro'}).click();await expect(page.locator('.receipt h2')).toHaveText('V-101');const receipt=page.waitForEvent('download');await page.getByRole('button',{name:'Descargar comprobante'}).click();expect((await receipt).suggestedFilename()).toBe('V-101-demo.txt');await page.evaluate(()=>window.print=()=>{});await page.getByRole('button',{name:'Imprimir',exact:true}).click();await page.getByRole('link',{name:'Reportes',exact:true}).click();await page.getByLabel('Desde',{exact:true}).fill('2099-01-01');await expect(page.getByText('Sin ventas en el período.',{exact:false})).toBeVisible();const report=page.waitForEvent('download');await page.getByRole('button',{name:'Exportar reporte'}).click();expect((await report).suggestedFilename()).toBe('reporte-demo.csv');await page.getByRole('button',{name:'Limpiar filtros'}).click();
});
test('cash close/open, sales pagination and mobile drawer',async({page})=>{
 await page.goto('/demo/caja');await page.getByLabel('Efectivo declarado (ARS)').fill('0');await page.getByRole('button',{name:'Confirmar cierre'}).click();await page.getByRole('button',{name:'Cancelar',exact:true}).click();await page.getByLabel('Motivo si hay diferencia').fill('Arqueo demo');await page.getByRole('button',{name:'Confirmar cierre'}).click();await page.getByRole('button',{name:'Confirmar',exact:true}).click();await expect(page.locator('.cash-pill')).toContainText('Caja cerrada');await page.getByLabel('Fondo inicial (ARS)').fill('25000');await page.getByRole('button',{name:'Abrir caja',exact:true}).click();await expect(page.locator('.cash-pill')).toContainText('Caja abierta');await page.getByRole('link',{name:'Ventas',exact:true}).click();await page.getByRole('button',{name:'Siguiente'}).click();await page.getByRole('button',{name:'Anterior'}).click();await page.getByLabel('Buscar',{exact:true}).fill('missing');await expect(page.getByText('No hay ventas para estos filtros.',{exact:false})).toBeVisible();await page.getByRole('button',{name:'Limpiar filtros'}).first().click();await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Abrir navegación'}).click();await page.getByRole('link',{name:'Productos',exact:true}).click();await expect(page.getByRole('heading',{name:'Productos',exact:true})).toBeVisible();await expect(page.getByRole('link',{name:'Inventario',exact:true})).not.toBeVisible();
});
