import { test, expect } from '@playwright/test';

const confirm=async(page:import('@playwright/test').Page)=>page.getByRole('button',{name:'Confirmar',exact:true}).click();
test('SH-SKIP preserves low-stock path query product set and keyboard focus',async({page})=>{
 await page.goto('/demo/inventario?stock=low');await expect(page.locator('.product-card')).toHaveCount(5);const before=await page.locator('.product-card .sku').allTextContents();await page.locator('.skip').focus();await page.locator('.skip').click();const url=new URL(page.url());expect(url.pathname).toBe('/demo/inventario');expect(url.search).toBe('?stock=low');expect(url.hash).toBe('#demo-main');await expect(page.locator('#demo-main')).toBeFocused();await expect(page.getByLabel('Stock bajo o agotado')).toBeChecked();await expect(page.locator('.product-card')).toHaveCount(5);expect(await page.locator('.product-card .sku').allTextContents()).toEqual(before);
});
test('all sale and customer row actions use the selected identity',async({page})=>{
 await page.goto('/demo/ventas');for(let i=90;i<98;i++){await page.getByLabel('Buscar',{exact:true}).fill(`V-${i}`);await page.locator('tbody tr').getByRole('link',{name:'Ver detalle'}).click();await expect(page.locator('.receipt h2')).toHaveText(`V-${i}`);await page.locator('nav').getByRole('link',{name:'Ventas',exact:true}).click();}
 await page.locator('nav').getByRole('link',{name:'Clientes',exact:true}).click();for(let i=0;i<7;i++){const card=page.locator('.customer-grid article').nth(i);const name=await card.locator('h2').innerText();if(i){await card.getByRole('button',{name:'Editar',exact:true}).click();await expect(page.getByLabel('Nombre',{exact:true})).toHaveValue(name);await page.getByRole('button',{name:'Guardar cliente'}).click();}await card.getByRole('button',{name:'Ver historial'}).click();await expect(page.getByRole('dialog').locator('h2')).toContainText(name);await page.getByRole('dialog').getByRole('button',{name:'Cerrar',exact:true}).click();await card.getByRole('button',{name:'Ver historial'}).click();await page.getByRole('button',{name:'Iniciar venta para este cliente'}).click();await expect(page.locator('.cart select')).toHaveValue(`c${i}`);await page.locator('nav').getByRole('link',{name:'Clientes',exact:true}).click();}
});
test('empty navigation and closed navigation expose working recovery links',async({page})=>{
 await page.goto('/demo/escenarios');await page.getByLabel('Estado inicial').selectOption({label:'Sin ventas'});await page.getByRole('button',{name:'Cargar escenario',exact:false}).click();await confirm(page);await page.getByRole('link',{name:'Crear la primera'}).click();await expect(page).toHaveURL(/pos$/);await page.getByRole('link',{name:'Escenarios',exact:true}).click();await page.getByLabel('Estado inicial').selectOption({label:'Caja cerrada'});await page.getByRole('button',{name:'Cargar escenario',exact:false}).click();await confirm(page);await page.locator('.shortcut').filter({hasText:'Abrir caja'}).click();await expect(page.getByRole('button',{name:'Abrir caja',exact:true})).toBeVisible();await page.getByRole('link',{name:'Nueva venta',exact:true}).click();await page.locator('.product-card').first().getByRole('button',{name:'Agregar',exact:false}).click();await page.getByRole('link',{name:'Continuar al pago'}).click();await page.getByRole('radio',{name:'Efectivo',exact:true}).check();await expect(page.getByRole('button',{name:'Confirmar cobro'})).toBeDisabled();await page.getByRole('link',{name:'Volver al carrito',exact:false}).click();await page.locator('.cart').getByRole('link',{name:'Abrir caja',exact:true}).click();await expect(page.getByRole('button',{name:'Abrir caja',exact:true})).toBeVisible();await page.locator('.cash-pill').click();await expect(page).toHaveURL(/caja$/);
});
test('customer clear and customer empty history and customer form fields produce visible results',async({page})=>{
 await page.goto('/demo/clientes');await page.getByLabel('Buscar cliente').fill('Ana Demo');await expect(page.locator('.customer-grid article')).toHaveCount(1);await page.getByRole('button',{name:'Limpiar',exact:true}).click();await expect(page.locator('.customer-grid article')).toHaveCount(7);await page.locator('.customer-grid article').first().getByRole('button',{name:'Ver historial'}).click();await expect(page.getByRole('dialog')).toContainText('Todavía no registra compras');await page.getByRole('dialog').getByRole('button',{name:'Cerrar',exact:true}).click();await page.getByRole('button',{name:'Nuevo cliente'}).click();await page.getByLabel('Nombre',{exact:true}).fill('Cliente completo');await page.getByLabel('Email opcional').fill('completo@example.invalid');await page.getByLabel('Teléfono opcional').fill('000-0000');await page.getByRole('button',{name:'Guardar cliente'}).click();await expect(page.locator('.customer-grid article').last()).toContainText('completo@example.invalid');await expect(page.locator('.customer-grid article').last()).toContainText('000-0000');
});
test('receipt navigation and cash print invoke the chosen printable view',async({page})=>{
 await page.goto('/demo/ventas');await page.locator('tbody tr').first().getByRole('link',{name:'Ver detalle'}).click();await expect(page.locator('.receipt')).toContainText('V-90');await page.evaluate(()=>{window.print=()=>{document.body.dataset['printed']='yes';};});await page.getByRole('button',{name:'Imprimir',exact:true}).click();await expect(page.locator('body')).toHaveAttribute('data-printed','yes');await page.evaluate(()=>delete document.body.dataset['printed']);await page.getByRole('link',{name:'Caja',exact:true}).click();await page.getByRole('button',{name:'Imprimir resumen'}).click();await expect(page.locator('body')).toHaveAttribute('data-printed','yes');
});
test('pending navigation resumes the terminal and cancellation preserves the cart',async({page})=>{
 await page.goto('/demo/pos');await page.locator('.product-card').first().getByRole('button',{name:'Agregar',exact:false}).click();await page.getByRole('link',{name:'Continuar al pago'}).click();await page.getByRole('radio',{name:'Tarjeta',exact:true}).check();await page.getByRole('button',{name:'Confirmar cobro'}).click();await page.getByRole('link',{name:'Volver al carrito',exact:false}).click();await expect(page.locator('.cart-line')).toHaveCount(1);await page.getByRole('link',{name:'Continuar al pago'}).click();await expect(page.locator('.terminal')).toContainText('Esperando confirmación');await page.getByRole('link',{name:'Cancelar pago y conservar carrito'}).click();await expect(page.locator('.cart-line')).toHaveCount(1);
});
test('SH-NAV/DB-LINK: all shell destinations and dashboard shortcuts land on their named page',async({page})=>{
 await page.goto('/demo');for(const [label,path] of [['Inicio','/demo'],['Nueva venta','/demo/pos'],['Ventas','/demo/ventas'],['Productos','/demo/productos'],['Inventario','/demo/inventario'],['Clientes','/demo/clientes'],['Caja','/demo/caja'],['Reportes','/demo/reportes'],['Escenarios','/demo/escenarios']]){await page.locator('nav').getByRole('link',{name:label,exact:true}).click();await expect(page).toHaveURL(new RegExp(path+'$'));}await page.getByRole('link',{name:'BlackStore COMERCIO',exact:false}).click();await page.locator('.skip').focus();await page.locator('.skip').click();await expect(page).toHaveURL(/#demo-main$/);await page.getByRole('link',{name:'Comenzar una venta'}).click();await expect(page).toHaveURL(/pos$/);await page.locator('nav').getByRole('link',{name:'Inicio',exact:true}).click();for(const [label,path] of [['Ventas registradas','ventas'],['Ventas netas','reportes'],['Efectivo en caja','caja'],['Ver ventas','ventas'],['Explorar productos','productos'],['Registrar cliente','clientes'],['Revisar caja','caja']]){await page.getByRole('link',{name:label,exact:false}).first().click();await expect(page).toHaveURL(new RegExp(path+'$'));await page.locator('nav').getByRole('link',{name:'Inicio',exact:true}).click();}await page.locator('.list-row').first().click();await expect(page.locator('.receipt')).toBeVisible();await page.locator('nav').getByRole('link',{name:'Reportes',exact:true}).click();await page.getByRole('link',{name:'Explorar comprobantes'}).click();await expect(page).toHaveURL(/ventas$/);await page.goto('/demo/ventas/missing');await page.getByRole('link',{name:'Volver a las ventas'}).click();await expect(page).toHaveURL(/ventas$/);
 await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Abrir navegación'}).click();await page.getByRole('button',{name:'Cerrar menú'}).click();await expect(page.getByRole('dialog',{name:'Navegación de BlackStore'})).toHaveCount(0);
});
test('ROLE-RESTRICTIONS: cashier stock, discount and cash close deny visibly and preserve state',async({page})=>{
 await page.goto('/demo/escenarios');await page.getByLabel('Rol ficticio').selectOption({label:'Cajero'});await page.getByRole('link',{name:'Probar una venta'}).click();await page.locator('.product-card').first().getByRole('button',{name:'Agregar',exact:false}).click();await page.getByLabel('Descuento autorizado (%)').fill('10');await page.getByRole('button',{name:'Aplicar descuento'}).click();await expect(page.getByRole('alert')).toContainText('Encargada');await expect(page.locator('.total')).toContainText('0 % descuento');await page.getByRole('button',{name:'Cerrar error'}).click();await expect(page.getByRole('alert')).toHaveCount(0);await page.getByRole('link',{name:'Inventario',exact:true}).click();await page.locator('.product-card').first().getByRole('button',{name:'Ajustar stock'}).click();await page.getByLabel('Ajuste de unidades').fill('1');await page.getByLabel('Motivo',{exact:true}).fill('No permitido');await page.getByRole('button',{name:'Registrar ajuste'}).click();await expect(page.getByRole('dialog').getByRole('alert')).toContainText('Encargada');await expect(page.getByRole('dialog')).toContainText('2 disponibles');await page.keyboard.press('Escape');await page.getByRole('link',{name:'Caja',exact:true}).click();await page.getByRole('button',{name:'Confirmar cierre'}).click();await confirm(page);await expect(page.getByRole('alert')).toContainText('Encargada');await expect(page.locator('.cash-pill')).toContainText('Caja abierta');await page.getByLabel('Importe (ARS)').fill('10');await page.getByLabel('Motivo / categoría').fill('No permitido');await page.getByRole('button',{name:'Guardar movimiento'}).click();await expect(page.getByRole('alert')).toContainText('Encargada');
});
test('DB-LOW: dashboard card opens the same active low stock set and count',async({page})=>{
 await page.goto('/demo');const card=page.getByRole('link',{name:'Stock bajo',exact:false});const count=Number(await card.locator('strong').innerText());await card.click();await expect(page).toHaveURL(/inventario\?stock=low$/);await expect(page.getByLabel('Stock bajo o agotado')).toBeChecked();await expect(page.locator('.product-card')).toHaveCount(count);expect(await page.locator('.product-card .status').allTextContents()).toEqual(['2 disponibles','0 disponibles','2 disponibles','2 disponibles','2 disponibles']);await page.getByLabel('Stock bajo o agotado').uncheck();await expect(page.locator('.product-card')).toHaveCount(18);
});
test('CAT-FILTER/DETAIL: all categories, low-stock and every catalogue detail render coherent outcomes',async({page})=>{test.setTimeout(60000);
 for(const route of ['pos','productos','inventario']){await page.goto('/demo/'+route);for(const [category,count] of [['Indumentaria',8],['Calzado',3],['Accesorios',5],['Básicos',2]] as const){await page.getByLabel('Categoría').selectOption({label:category});await expect(page.locator('.product-card')).toHaveCount(count);}await page.getByRole('button',{name:'Limpiar',exact:true}).click();await page.getByLabel('Stock bajo o agotado').check();await expect(page.locator('.product-card')).toHaveCount(5);await page.getByRole('button',{name:'Limpiar',exact:true}).click();await page.getByLabel('Buscar producto').fill('sin coincidencias');await expect(page.getByRole('heading',{name:'No encontramos productos'})).toBeVisible();await page.getByRole('button',{name:'Limpiar filtros',exact:true}).click();for(let i=0;i<18;i++){const card=page.locator('.product-card').nth(i);await card.locator('.product-art').click();await expect(page.getByRole('dialog')).toBeVisible();await page.getByRole('dialog').getByRole('button',{name:'Cerrar',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);if(route==='pos'){const add=card.getByRole('button',{name:'Agregar',exact:false});if(await add.count()&&await add.isEnabled()){await add.click();await expect(page.locator('.cart-line')).toHaveCount(1);await page.getByRole('button',{name:'Quitar producto'}).click();await expect(page.locator('.cart-line')).toHaveCount(0);}else await expect(card.locator('.primary')).toBeDisabled();}if(route==='productos'){await card.getByRole('button',{name:'Editar',exact:true}).click();await page.getByRole('button',{name:'Guardar producto'}).click();const original=await card.getByRole('button',{name:/^(Activar|Desactivar)$/}).innerText();await card.getByRole('button',{name:original,exact:true}).click();await card.getByRole('button',{name:original==='Activar'?'Desactivar':'Activar',exact:true}).click();await expect(card.getByRole('button',{name:original,exact:true})).toBeVisible();}if(route==='inventario'){await card.getByRole('button',{name:'Ajustar stock'}).click();await page.getByLabel('Ajuste de unidades').fill('1');await page.getByLabel('Motivo',{exact:true}).fill('Cancelado');await page.getByRole('dialog').getByRole('button',{name:'Cerrar',exact:true}).click();}}}
});
test('PO-CART/MODAL: quantity, customer, discounts, empty cancel/confirm and detail addition',async({page})=>{
 await page.goto('/demo/productos');
 await page.locator('.product-card').first().locator('.product-art').click();await page.getByRole('dialog').getByRole('button',{name:'Agregar al carrito'}).click();await page.getByRole('dialog').getByRole('button',{name:'Cerrar',exact:true}).click();await page.locator('nav').getByRole('link',{name:'Nueva venta',exact:true}).click();await expect(page.locator('.cart-line')).toHaveCount(1);await page.getByRole('button',{name:'Aumentar cantidad'}).click();await page.getByRole('button',{name:'Disminuir cantidad'}).click();await page.getByLabel('Cantidad de Remera esencial').fill('2');await expect(page.locator('.cart-line')).toContainText('25.000,00');await page.getByLabel('Cliente').selectOption({label:'Ana Demo'});await page.getByLabel('Descuento autorizado (%)').fill('10');await page.getByRole('button',{name:'Aplicar descuento'}).click();await expect(page.locator('.total')).toContainText('22.500,00');await page.getByLabel('Descuento autorizado (%)').fill('0');await page.getByRole('button',{name:'Aplicar descuento'}).click();await expect(page.locator('.total')).toContainText('25.000,00');await page.getByRole('button',{name:'Vaciar carrito'}).click();await page.getByRole('alertdialog').getByRole('button',{name:'Cancelar',exact:true}).click();await expect(page.locator('.cart-line')).toHaveCount(1);await page.getByRole('button',{name:'Vaciar carrito'}).click();await confirm(page);await expect(page.locator('.cart-line')).toHaveCount(0);await expect(page.getByLabel('Cliente')).toHaveValue('c0');await page.locator('.product-card').first().getByRole('button',{name:'Agregar',exact:false}).click();await page.getByRole('button',{name:'Quitar producto'}).click();await expect(page.locator('.cart-line')).toHaveCount(0);
});
test('VE-FILTER/RP-PERIOD: date, status, method, customer search and filtered exports',async({page})=>{
 await page.goto('/demo/ventas');await page.getByLabel('Estado').selectOption({label:'Completada'});await expect(page.locator('.pagination')).toContainText('7 ventas');await page.getByLabel('Estado').selectOption({label:'Devuelta'});await expect(page.locator('tbody tr')).toHaveCount(1);await expect(page.locator('tbody tr')).toContainText('Devuelta');await page.getByRole('button',{name:'Limpiar filtros',exact:true}).click();for(const [label,count]of [['Efectivo',3],['Tarjeta',3],['Transferencia',2],['QR',0]] as const){await page.getByLabel('Medio').selectOption({label});if(count)await expect(page.locator('tbody tr')).toHaveCount(count);else await expect(page.getByText('No hay ventas para estos filtros.',{exact:false})).toBeVisible();}await page.getByLabel('Medio').selectOption({label:'Efectivo'});await expect(page.locator('tbody tr')).toHaveCount(3);await page.getByLabel('Buscar',{exact:true}).fill('Ana Demo');await expect(page.locator('tbody tr')).toHaveCount(2);await page.getByLabel('Desde',{exact:true}).fill('2099-01-01');await page.getByLabel('Hasta',{exact:true}).fill('2099-01-31');await expect(page.getByText('No hay ventas para estos filtros.',{exact:false})).toBeVisible();await page.getByRole('button',{name:'Limpiar filtros',exact:true}).last().click();await page.getByRole('link',{name:'Reportes',exact:true}).click();await page.getByLabel('Desde',{exact:true}).fill('2099-01-01');await page.getByLabel('Hasta',{exact:true}).fill('2099-01-31');await expect(page.getByText('Sin ventas en el período.',{exact:false})).toBeVisible();await page.getByRole('link',{name:'registrá una venta'}).click();await expect(page.getByRole('heading',{name:'Nueva venta',exact:true})).toBeVisible();
});
test('MODALS/CLIENTS: cancel create/edit, search clear, history navigation and reversal cancel',async({page})=>{
 await page.goto('/demo/productos');await page.getByRole('button',{name:'Crear producto'}).click();await page.getByLabel('Nombre',{exact:true}).fill('No guardar');await page.getByRole('dialog').getByRole('button',{name:'Cerrar',exact:true}).click();await expect(page.locator('.product-card')).toHaveCount(18);await page.locator('.product-card').first().getByRole('button',{name:'Editar',exact:true}).click();await page.getByLabel('Nombre',{exact:true}).fill('Cambio cancelado');await page.keyboard.press('Escape');await expect(page.locator('.product-card').first()).toContainText('Remera esencial');await page.getByRole('link',{name:'Clientes',exact:true}).click();await page.getByRole('button',{name:'Nuevo cliente'}).click();await page.getByLabel('Nombre',{exact:true}).fill('Cancelado');await page.getByRole('dialog').getByRole('button',{name:'Cerrar',exact:true}).click();await expect(page.locator('.customer-grid article')).toHaveCount(7);await page.locator('.customer-grid article').nth(1).getByRole('button',{name:'Editar',exact:true}).click();await page.getByLabel('Nombre',{exact:true}).fill('No guardar cliente');await page.getByRole('dialog').getByRole('button',{name:'Cerrar',exact:true}).click();await expect(page.locator('.customer-grid article').nth(1)).toContainText('Ana Demo');await page.getByLabel('Buscar cliente').fill('nadie');await expect(page.getByText('No encontramos clientes.',{exact:false})).toBeVisible();await page.getByRole('button',{name:'Limpiar búsqueda'}).click();await page.locator('.customer-grid article').nth(1).getByRole('button',{name:'Ver historial'}).click();await page.getByRole('dialog').getByRole('link').first().click();await expect(page.locator('.receipt')).toBeVisible();await page.getByLabel('Motivo de devolución').fill('Cancelar devolución');await page.getByRole('button',{name:'Registrar devolución'}).click();await page.getByRole('alertdialog').getByRole('button',{name:'Cancelar',exact:true}).click();await expect(page.locator('.receipt')).toContainText('Completada');await expect(page.getByRole('button',{name:'Registrar devolución'})).toBeVisible();await page.locator('.receipt').getByRole('link',{name:'Nueva venta',exact:true}).click();await expect(page).toHaveURL(/pos$/);
});
test('SC-ALL/ROLE/CA-FILTER: each scenario reset, cancel reset, slow recovery, profiles and movement filtering',async({page})=>{
 await page.goto('/demo/escenarios');await page.getByLabel('Estado inicial').selectOption({label:'Caja cerrada'});await page.getByRole('button',{name:'Cargar escenario',exact:false}).click();await page.getByRole('alertdialog').getByRole('button',{name:'Cancelar',exact:true}).click();await expect(page.locator('.cash-pill')).toContainText('Caja abierta');for(const scenario of ['Comercio en marcha','Caja cerrada','Sin ventas','Stock bajo','Error recuperable al cobrar','Carga lenta']){await page.getByLabel('Estado inicial').selectOption({label:scenario});await page.getByRole('button',{name:'Cargar escenario',exact:false}).click();await confirm(page);await expect(page.getByRole('heading',{name:'Buen día, Marina',exact:false})).toBeVisible();if(scenario==='Carga lenta'){await expect(page.getByRole('status').filter({hasText:'Cargando datos'})).toBeVisible();await expect(page.getByRole('link',{name:'Comenzar una venta'})).toBeVisible();}if(scenario==='Sin ventas')await expect(page.getByText('Todavía no hay ventas.',{exact:false})).toBeVisible();if(scenario==='Caja cerrada')await expect(page.locator('.cash-pill')).toContainText('Caja cerrada');await page.getByRole('link',{name:'Escenarios',exact:true}).click();await expect(page.getByLabel('Estado inicial')).toBeVisible();}
 await page.getByLabel('Rol ficticio').selectOption({label:'Cajero'});await expect(page.locator('.rail-footer')).toContainText('Cajero');await page.getByLabel('Rol ficticio').selectOption({label:'Encargada'});await expect(page.locator('.rail-footer')).toContainText('Encargada');await page.getByRole('link',{name:'Caja',exact:true}).click();await page.getByLabel('Tipo').selectOption({label:'Ingreso'});await page.getByLabel('Importe (ARS)').fill('10');await page.getByLabel('Motivo / categoría').fill('Ingreso prueba');await page.getByRole('button',{name:'Guardar movimiento'}).click();await page.getByLabel('Filtrar motivo').fill('Ingreso prueba');await expect(page.locator('.list-row')).toHaveCount(1);await expect(page.locator('.list-row')).toContainText('Ingreso prueba');
});
