import { test, expect } from '@playwright/test';
test('cash count starts in ARS and closes without a difference before and after a sale',async({page})=>{
 await page.goto('/demo/caja');await expect(page.getByLabel('Efectivo declarado (ARS)')).toHaveValue('108200');await page.getByRole('button',{name:'Confirmar cierre'}).click();await page.getByRole('button',{name:'Confirmar',exact:true}).click();await expect(page.locator('.cash-pill')).toContainText('Caja cerrada');await expect(page.locator('.metric').filter({hasText:'Declarado / diferencia'})).toContainText('Sin diferencia');await expect(page.locator('.metric').filter({hasText:'Declarado / diferencia'})).toContainText('$ 0,00');
 await page.goto('/demo/pos');await page.locator('.product-card').first().getByRole('button',{name:'Agregar',exact:false}).click();await page.getByRole('link',{name:'Continuar al pago'}).click();await page.getByRole('radio',{name:'Efectivo',exact:true}).check();await page.getByLabel('Efectivo recibido (ARS)').fill('12500');await page.getByRole('button',{name:'Confirmar cobro'}).click();await page.getByRole('link',{name:'Caja',exact:true}).click();await expect(page.getByLabel('Efectivo declarado (ARS)')).toHaveValue('120700');await page.getByRole('button',{name:'Confirmar cierre'}).click();await page.getByRole('button',{name:'Confirmar',exact:true}).click();await expect(page.locator('.cash-pill')).toContainText('Caja cerrada');await expect(page.locator('.metric').filter({hasText:'Declarado / diferencia'})).toContainText('Sin diferencia');await expect(page.locator('.metric').filter({hasText:'Declarado / diferencia'})).toContainText('$ 0,00');
});

for(const method of ['Tarjeta','Transferencia','QR']){
 test(`${method}: pending, rejection, retry, cancel and approval preserve the sale`,async({page})=>{
  const api:string[]=[];page.on('request',r=>{if(r.url().includes('/api/')||r.url().includes(':808'))api.push(r.url());});
  await page.goto('/demo/pos');await page.locator('.product-card').first().getByRole('button',{name:'Agregar',exact:false}).click();
  await page.getByRole('link',{name:'Continuar al pago'}).click();await page.getByRole('radio',{name:method,exact:true}).check();await page.getByLabel('Referencia opcional').fill('PAGO-DEMO-001');await page.getByRole('button',{name:'Confirmar cobro'}).click();
  await expect(page.locator('.terminal')).toContainText('Esperando confirmación');await expect(page.locator('.terminal')).toBeFocused();await expect(page.locator('.terminal')).toContainText('PAGO-DEMO-001');await expect(page.locator('.terminal')).toContainText('todavía no se descontó stock');
  await page.getByRole('button',{name:'Simular rechazo'}).click();await expect(page.getByRole('status').filter({hasText:'Pago rechazado'})).toBeVisible();await expect(page.locator('#demo-payment-retry')).toBeFocused();await expect(page.getByRole('heading',{name:'Resumen de compra'}).locator('..')).toContainText('1 × Remera esencial');
  await page.getByRole('button',{name:'Confirmar cobro'}).click();await page.getByRole('button',{name:'Cancelar intento'}).click();await expect(page.getByRole('status').filter({hasText:'Pago cancelado'})).toBeVisible();
  await page.getByRole('button',{name:'Confirmar cobro'}).click();await page.getByRole('link',{name:'Cancelar pago y conservar carrito'}).click();await expect(page.locator('.cart-line')).toHaveCount(1);
  await page.getByRole('link',{name:'Continuar al pago'}).click();await page.getByRole('radio',{name:method,exact:true}).check();await page.getByRole('button',{name:'Confirmar cobro'}).click();await page.getByRole('button',{name:'Simular aprobación'}).click();
  await expect(page.locator('.receipt')).toContainText('Pago aprobado');await expect(page.locator('.receipt')).toContainText('Entrega inmediata en mostrador');await expect(page.locator('.receipt')).toContainText(method);await expect(page.locator('.receipt h2')).toHaveText('V-101');expect(api).toEqual([]);
 });
}
test('mixed QR payment displays amount, change and a coherent receipt on mobile',async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.goto('/demo/pos');await page.locator('.product-card').first().getByRole('button',{name:'Agregar',exact:false}).click();await page.locator('.quick-cart').getByRole('button',{name:'Ver carrito'}).click();await page.getByRole('link',{name:'Continuar al pago'}).click();
 await page.getByRole('radio',{name:'QR',exact:true}).check();await page.getByLabel('Combinar con efectivo').check();await page.getByLabel('Parte en efectivo (ARS)').fill('5000');await page.getByLabel('Efectivo recibido (ARS)').fill('6000');await page.getByRole('button',{name:'Confirmar cobro'}).click();await expect(page.locator('.terminal')).toContainText('saldo electrónico:');await expect(page.getByRole('img',{name:'QR ficticio',exact:false})).toBeVisible();await page.screenshot({path:'demo-test-results/screenshots/390-qr-pending.png',fullPage:true});
 await page.getByRole('button',{name:'Simular aprobación'}).click();await expect(page.locator('.receipt')).toContainText('Efectivo:');await expect(page.locator('.receipt')).toContainText('Referencia:');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.setViewportSize({width:1440,height:1000});await page.getByRole('link',{name:'Inventario',exact:true}).click();await expect(page.locator('.product-card').first()).toContainText('1 disponibles');await page.locator('.product-card').first().getByRole('button',{name:'Ajustar stock'}).click();await expect(page.getByRole('dialog')).toContainText('Venta V-101');await page.keyboard.press('Escape');await page.getByRole('link',{name:'Ventas',exact:true}).click();await page.getByLabel('Buscar',{exact:true}).fill('V-101');await expect(page.locator('tbody tr')).toHaveCount(1);await expect(page.locator('tbody tr')).toContainText('QR');await page.getByRole('link',{name:'Reportes',exact:true}).click();await expect(page.locator('.report-row').filter({hasText:'QR'})).toContainText('7.500,00');await expect(page.locator('.report-row').filter({hasText:'Efectivo'})).toContainText('63.200,00');await page.getByRole('link',{name:'Caja',exact:true}).click();await expect(page.getByRole('heading',{name:'Caja',exact:true})).toBeVisible();await expect(page.locator('.metric').filter({hasText:'Efectivo esperado'})).toContainText('113.200,00');
});
test('cashier can sell and manage customer data while manager commands show recoverable denial',async({page})=>{
 await page.goto('/demo/escenarios');await page.getByLabel('Rol ficticio').selectOption('cashier');await page.getByRole('link',{name:'Productos',exact:true}).click();await page.locator('.product-card').first().getByRole('button',{name:'Editar',exact:true}).click();await page.getByLabel('Precio (ARS)').fill('1');await page.getByRole('button',{name:'Guardar producto'}).click();await expect(page.getByRole('dialog').getByRole('alert')).toContainText('Encargada');await page.keyboard.press('Escape');await page.getByRole('link',{name:'Clientes',exact:true}).click();await page.getByRole('button',{name:'Nuevo cliente'}).click();await page.getByLabel('Nombre',{exact:true}).fill('Cliente cajero demo');await page.getByRole('button',{name:'Guardar cliente'}).click();await expect(page.getByRole('heading',{name:'Cliente cajero demo'})).toBeVisible();await page.getByRole('link',{name:'Nueva venta',exact:true}).click();await page.locator('.product-card').first().getByRole('button',{name:'Agregar',exact:false}).click();await page.getByRole('link',{name:'Continuar al pago'}).click();await page.getByRole('radio',{name:'Efectivo',exact:true}).check();await page.getByLabel('Efectivo recibido (ARS)').fill('12500');await page.getByRole('button',{name:'Confirmar cobro'}).click();await expect(page.locator('.receipt')).toContainText('Cajero Demo');await page.getByLabel('Motivo de devolución').fill('Prueba permiso');await page.getByRole('button',{name:'Registrar devolución'}).click();await page.getByRole('button',{name:'Confirmar',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Encargada');await expect(page.locator('.receipt')).toContainText('Completada');
});
test('compact POS keeps product search available while browsing and local illustrations load',async({page})=>{
 for(const width of [390,768,1440]){await page.setViewportSize({width,height:844});await page.goto('/demo/pos');await expect(page.locator('.product-art img')).toHaveCount(18);expect(await page.locator('.product-art img').evaluateAll(images=>images.every(img=>(img as HTMLImageElement).complete&&(img as HTMLImageElement).naturalWidth>0))).toBe(true);await page.locator('.product-card').last().scrollIntoViewIfNeeded();if(width<=900)await expect(page.getByLabel('Buscar producto')).toBeInViewport();await page.getByLabel('Buscar producto').fill('Camisa');await expect(page.locator('.product-card')).toHaveCount(1);await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:`demo-test-results/screenshots/${width}-compact-pos.png`,fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}
});
test('operator creates catalogue item, stocks it, sells it and sees low-stock alert plus history',async({page})=>{
 await page.goto('/demo/productos');await page.getByRole('button',{name:'Crear producto'}).click();await page.getByLabel('Nombre',{exact:true}).fill('Artículo presentación');await page.getByLabel('SKU',{exact:true}).fill('BS-PRESENTACION');await page.getByLabel('Precio (ARS)').fill('5000');await page.getByRole('button',{name:'Guardar producto'}).click();await page.getByRole('link',{name:'Inventario',exact:true}).click();await page.getByLabel('Buscar producto').fill('Artículo presentación');await page.getByRole('button',{name:'Ajustar stock'}).click();await page.getByLabel('Ajuste de unidades').fill('5');await page.getByLabel('Motivo',{exact:true}).fill('Carga inicial demo');await page.getByRole('button',{name:'Registrar ajuste'}).click();await expect(page.getByRole('dialog')).toContainText('5 disponibles');await page.keyboard.press('Escape');await page.getByRole('link',{name:'Nueva venta',exact:true}).click();await page.getByLabel('Buscar producto').fill('Artículo presentación');await page.getByRole('button',{name:'Agregar',exact:false}).click();await page.getByRole('button',{name:'Aumentar cantidad'}).click();await page.getByRole('button',{name:'Aumentar cantidad'}).click();await page.getByRole('link',{name:'Continuar al pago'}).click();await page.getByRole('radio',{name:'Transferencia',exact:true}).check();await page.getByRole('button',{name:'Confirmar cobro'}).click();await page.getByRole('button',{name:'Simular aprobación'}).click();await expect(page.locator('.receipt')).toContainText('3 × Artículo presentación');await page.getByRole('link',{name:'Inventario',exact:true}).click();await page.getByLabel('Buscar producto').fill('Artículo presentación');await expect(page.locator('.product-card')).toContainText('2 disponibles');await expect(page.locator('.product-card .status')).toHaveClass(/warning/);await page.getByRole('button',{name:'Ajustar stock'}).click();await expect(page.getByRole('dialog')).toContainText('Carga inicial demo');await expect(page.getByRole('dialog')).toContainText('Venta V-');
});
