import { test, expect } from './fixtures/dct-runtime';
import { StaffSessionPage } from './pages/staff-session-page';
import { CashSessionPage } from './pages/cash-session-page';
import { CashSessionStatus, PaymentMethod, StaffRole } from '../../src/app/core/domain/pos-types';
import { DctAuditEvent } from './fixtures/dct-audit-event';

test('cash-browser-restart: real cash facts and staff session survive a new JAR PID without replay', async ({ runtime, page }) => {
  const staff = await runtime.database.seed(StaffRole.Cashier);
  const terminal = await runtime.database.terminal();
  await new StaffSessionPage(page).login(staff);
  const cashPage = new CashSessionPage(page);
  await cashPage.visit(terminal);
  const cashId = await cashPage.open('100');
  await cashPage.expense('7.25');
  await cashPage.close(cashId, '92.75');
  const before = await runtime.database.facts(cashId);
  expect(before.cash.status).toBe(CashSessionStatus.Closed);
  expect(before.cash.opening_cash).toBe('100.00');
  expect(before.cash.closing_cash_declared).toBe('92.75');
  expect(Number(before.cash.cashier_id)).toBe(staff.id);
  expect(Number(before.cash.terminal_id)).toBe(terminal);
  expect((await runtime.database.query("SELECT active FROM staff_users WHERE login='cashier'"))[0].active).toBe(false);
  expect((await runtime.database.query('SELECT max(version::int) AS version FROM flyway_schema_history WHERE success'))[0].version).toBe(7);
  expect(before.expenses).toHaveLength(1);
  expect(before.expenses[0].amount).toBe('7.25');
  expect(Number(before.expenses[0].created_by)).toBe(staff.id);
  expect(PaymentMethod.fromWire(before.expenses[0].payment_method)).toBe(PaymentMethod.Cash);
  expect(before.audit).toHaveLength(3);
  expect(before.audit.every(row => Number(row.actor_id) === staff.id)).toBe(true);
  expect(before.audit.map(row => row.event_type)).toEqual([DctAuditEvent.Opened, DctAuditEvent.ExpenseRecorded, DctAuditEvent.Closed]);
  expect(before.audit.map(row => Number(row.aggregate_id))).toEqual([cashId, Number(before.expenses[0].id), cashId]);
  expect(before.audit.every(row => row.occurred_at instanceof Date)).toBe(true);
  expect(new Date(before.cash.closed_at).getTime()).toBeGreaterThanOrEqual(new Date(before.cash.opened_at).getTime());
  await runtime.restartBackend();
  const posts: string[] = [];
  page.on('request', request => { if (request.method() === 'POST' && /\/api\/v1\/(cash-sessions|expenses)/.test(request.url())) posts.push(request.url()); });
  const readback = page.waitForResponse(r => r.url().endsWith('/api/v1/cash-sessions') && r.request().method() === 'GET');
  const sid = page.waitForResponse(r => r.url().endsWith('/api/v1/auth/session'));
  await page.reload();
  const identityResponse = await sid;
  expect(identityResponse.status()).toBe(200);
  const response = await readback;
  expect(response.status()).toBe(200);
  await expect(page.locator('header .role')).toContainText(staff.displayName);
  await cashPage.expectClosedWorkstation(terminal, staff.id);
  expect(posts).toEqual([]);
  expect(await runtime.database.facts(cashId)).toEqual(before);
});
